Numpy

In [ ]:
!pip install numpy

Load in NumPy

In [1]:
import numpy as np

**Basics Stuff**

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b=np.array([[1,3],[2,6]])
b

array([[1, 3],
       [2, 6]])

Dimension

In [6]:
b.ndim

2

Shape

In [7]:
b.shape

(2, 2)

Type

In [8]:
b.dtype

dtype('int64')

Size in bytes

In [9]:
b.itemsize

8

Total size

In [10]:
b.nbytes

32

**Accessing/Changing specific elements,rows,columns, etc**

---



In [16]:
a=np.array([[1,2,6],[2,5,9],[6,3,8],[7,6,2]])
a

array([[1, 2, 6],
       [2, 5, 9],
       [6, 3, 8],
       [7, 6, 2]])

Get a specific element[r,c]

In [17]:
a[1,2]

9

Get a specific row

In [18]:
a[1,:]

array([2, 5, 9])

Get a specific column

In [19]:
a[:,2]

array([6, 9, 8, 2])

Part of a array

In [25]:
a[0:-2,1:-1]

array([[2],
       [5]])

Change the value


In [27]:
a[1,1]=25
a

array([[ 1,  2,  6],
       [ 2, 25,  9],
       [ 6,  3,  8],
       [ 7,  6,  2]])

In [30]:
a[:,2]=[1,2,3,4]
a

array([[ 1,  2,  1],
       [ 2, 25,  2],
       [ 6,  3,  3],
       [ 7,  6,  4]])

3D Array

In [32]:
c=np.array([[[1,2,3],[4,2,1]],[[6,3,7],[5,6,9]]])
c

array([[[1, 2, 3],
        [4, 2, 1]],

       [[6, 3, 7],
        [5, 6, 9]]])

Get specific Element

In [34]:
c[0,1,:]

array([4, 2, 1])

Replace 

In [35]:
c[0,1,:]=[1,2,4]
c

array([[[1, 2, 3],
        [1, 2, 4]],

       [[6, 3, 7],
        [5, 6, 9]]])

**Initializing Different Types of Array**

Zeroes Matrix

In [41]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Ones Matrix 

In [44]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

Other number

In [45]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

Full_like

In [46]:
c=np.array([[[1,2,3],[4,2,1]],[[6,3,7],[5,6,9]]])
d=np.full_like(c,6)
d

array([[[6, 6, 6],
        [6, 6, 6]],

       [[6, 6, 6],
        [6, 6, 6]]])

Random decimal Numbers 

In [47]:
np.random.rand(4,3)

array([[0.22256894, 0.03016414, 0.33285384],
       [0.60527465, 0.11737709, 0.82658555],
       [0.81860634, 0.59780135, 0.15981456],
       [0.74526236, 0.98692948, 0.64152047]])

In [48]:
np.random.random_sample(c.shape)

array([[[0.8581125 , 0.81881027, 0.82410742],
        [0.13887286, 0.58967527, 0.1119762 ]],

       [[0.68213801, 0.11701467, 0.42094156],
        [0.55402649, 0.89649551, 0.0691587 ]]])

Random Integer value

In [49]:
np.random.randint(1,10,size=(3,3))

array([[5, 6, 5],
       [8, 4, 7],
       [8, 3, 5]])

Identity Matrix

In [51]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Repeat an array

In [52]:
e=np.array([[1,2,3]])
f=np.repeat(e,3,axis=0)
f

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

Copy Array

In [54]:
a=np.array([1,5,6])
b=a.copy()
b

array([1, 5, 6])

**Mathematics**

In [56]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

Addition

In [62]:
a+=10
a

Subtraction

In [60]:
print(a)
a-=100
a

[-99 -98 -97 -96]


array([-199, -198, -197, -196])

Multiple 

In [63]:
a*2

array([-358, -356, -354, -352])

Divide 

In [64]:
a/2

array([-89.5, -89. , -88.5, -88. ])

In [67]:
9b=np.array([2,1,3,4])
a=np.array([1,5,3,7])
c=a+b
c

array([ 3,  6,  6, 11])

sin()

In [69]:
np.sin(a)

array([ 0.84147098, -0.95892427,  0.14112001,  0.6569866 ])

**Linear Algebra**

Matrix Multiple 

In [72]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

Determinant

In [74]:
a=np.array([[2,4],[6,5]])
np.linalg.det(a)

-14.000000000000004

Inverse Matrix

In [75]:
np.linalg.inv(a)

array([[-0.35714286,  0.28571429],
       [ 0.42857143, -0.14285714]])

**Statistics**

In [77]:
sta=np.array([[1,1,5],[2,3,4]])
sta

array([[1, 1, 5],
       [2, 3, 4]])

In [78]:
np.min(sta,axis=0)

array([1, 1, 4])

In [79]:
np.max(sta)

5

In [80]:
np.sum(sta)

16

Reorganizing Arrays

In [82]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((4,2))
after

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Stacking

In [84]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**Miscellaneous**

Load Data

In [89]:
filedata=np.genfromtxt('data.txt',delimiter=',')
fdata=filedata.astype('int32')
filedata

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.]])

Booean Masking

In [90]:
fdata>10

array([[False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [92]:
fdata[fdata>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20], dtype=int32)

In [95]:
fdata[[1]]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]], dtype=int32)

In [98]:
fdata[[1],[1]]

array([12], dtype=int32)